build:
  image: python:2
  commands:
    - echo "Buliding..."

publish:
  docker:
    repo: $$DOCKER_USERNAME/$$DOCKER_REPO
    tag: "$${BRANCH##feature/}"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL

  docker:
    repo: $$DOCKER_USERNAME/$$DOCKER_REPO
    tag: "latest"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    when:
      branch: "master"

deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$MANTL_APP_NAME-$$BRANCH/restart?force=true
    when:
      branch: "!master"

notify:
  spark:
    image: hpreston/drone-spark
    roomId: $$SPARK_ROOM
    auth_token: $$SPARK_TOKEN
